### ISSUE TITLE
Implicit dependency on Haml

### ISSUE THREAD

**Issue by adzap** [dvandersluis/compendium#11]
I noticed that the default templates are in Haml, though Haml is not a gem dependency.

Given the templates are very small I wonder if just converting them to Erb is not a better approach to avoid having a potentially unused gem dependency on Haml if the apps using this gem don't use it.

**Comment by dvandersluis** [comment]
When I first put compendium together, it was a lot of extracting out of a project using Haml, so I didn't really think about it, but your point is good. I'm on board with converting the handful of default templates and removing the requirement.

**Comment by adzap** [comment]
Great, thanks.

On Tue, Feb 7, 2017 at 6:37 AM, Daniel Vandersluis <notifications@github.com> wrote:
When I first put compendium together, it was a lot of extracting out of a project using Haml, so I didn't really think about it, but your point is good. I'm on board with converting the handful of default templates and removing the requirement.

**Comment by dvandersluis** [comment]
Fixed in 150460e
