### ISSUE TITLE
Dynamic values for dropdown option?

### ISSUE THREAD

**Issue by adambedford** [dvandersluis/compendium#12]
Is it possible to have dynamic values for a dropdown based on `current_user` or similar?

i.e. 
`option :group, :dropdown, -> (user) { user.groups.pluck(:name) }` if the options can receive a user as an argument
or
`option :group, :dropdown, -> { current_user.groups.pluck(:name) }` if the options can be evaluated in the context of a request?

**Comment by dvandersluis** [comment]
You certainly can, you just need to pass in a lambda to the `choices` key:

```ruby
option :group, :dropdown, choices: -> * { current_user.groups.pluck(:name) }
```

**Comment by adambedford** [comment]
Perfect, thanks!
