### ISSUE TITLE
capistrano-sneakers

### ISSUE THREAD

**Issue by Tensho** [dvandersluis/compendium#14]
Sorry I disturb you here, but can't find another way to reach you. I use [`capistrano-sneakers`](https://github.com/Tensho/capistrano-sneakers) and contribute constantly. If I understand correctly you are not interested or don't have the time right now to maintain it. Is it possible to pass it's ownership at **rubygems** to me, so I could easily release new versions? 🙇

**Comment by dvandersluis** [comment]
I think you have the wrong user, it's not my gem.

**Comment by Tensho** [comment]
https://rubygems.org/profiles/dvandersluis

**Comment by Tensho** [comment]
https://rubygems.org/gems/capistrano-sneakers

**Comment by dvandersluis** [comment]
That is very strange, I guess someone put me in the gemspec, but I've never even heard of this gem until right now.

**Comment by Tensho** [comment]
Probably RubyGems misleads ownership...

**Comment by Tensho** [comment]
Is it possible to transfer ownership?

**Comment by Tensho** [comment]
http://guides.rubygems.org/command-reference/#gem-owner
`gem owner capistrano-sneakers -a andrew.babichev@gmail.com -r daniel@codexed.com`

**Comment by Tensho** [comment]
BTW, I dont' know is intentionally, but your email address `daniel@codexed.com` is bounced.

**Comment by dvandersluis** [comment]
Yeah that domain has been shut down for a couple years.

**Comment by Tensho** [comment]
Maybe you know this guy, Spirit :)
![screen shot 2018-01-26 at 16 51 38](https://user-images.githubusercontent.com/892721/35445122-4cd255f4-02b9-11e8-8fa3-6e9ba93d7e77.png)

**Comment by dvandersluis** [comment]
I'm afraid I don't know Spirit either. I'm not sure how I got involved in this in the first place. I am going to reach out to the @inventionlabsSydney as it seems that is the current owner of the github repo?

**Comment by Tensho** [comment]
Sure, I don't mind if you pass ownership to him. Thank will be great.

**Comment by Tensho** [comment]
@dvandersluis , any luck regarding my question? I don't want to pollute this repo with non-relevant stuff, so it would be nice if you give me some convenient contact for you, please 🙇
