### ISSUE TITLE
Would it be possible to customize the css class for the generated table?

### ISSUE THREAD

**Issue by cimtico** [dvandersluis/compendium#6]
Would it be possible to have a config hash that gets passed to render_table to set the table classes?

**Comment by dvandersluis** [comment]
What did you have in mind?

**Comment by cimtico** [comment]
render_table(self, {class: 'table table-with-stripes'})

this would add/set the specified table class to what was provided.

**Comment by dvandersluis** [comment]
Hm, i'll have to think about it. In the meantime, feel free to contribute a pull request and I'll take a look!

**Comment by dvandersluis** [comment]
@cimtico I updated compendium to allow you to specify any of 4 different CSS classes when rendering a table now (and closed your PR as it's now unnecessary). Thanks for the suggestion!

Please see [https://github.com/dvandersluis/compendium#css-classes](https://github.com/dvandersluis/compendium#css-classes) for details on how to set these settings.

Note that the gem has not yet been updated to include these changes, but they are in master.
